spring:
  datasource:
    url: jdbc:h2:mem:library
#    schema: sql/schema.sql
#    data: sql/data.sql
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

app:
  h2ConsoleEnabled: false
