spring:
  datasource:
    url: jdbc:h2:mem:library

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    ru.skubatko.dev: DEBUG
  file:
    name: ./logs/app.log

app:
  h2ConsoleEnabled: false
