/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.skubatko.dev.otus.spring.hw03;

import ru.skubatko.dev.otus.spring.hw03.config.AppProps;
import ru.skubatko.dev.otus.spring.hw03.controller.QuizController;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
@EnableConfigurationProperties(AppProps.class)
public class App {

    public static void main(String[] args) {
        ApplicationContext ctx = SpringApplication.run(App.class, args);
        QuizController controller = ctx.getBean(QuizController.class);
        controller.makeQuizzed();
    }
}
