spring:
  datasource:
    url: jdbc:h2:mem:library

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
#        format_sql: true

    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

app:
  h2ConsoleEnabled: false
