version: '3.8'

networks:
  default:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: otus-hw/library
    environment:
      TZ: 'Europe/Moscow'
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    ports:
      - 18081:8081
      - 15005:5005
    expose:
      - 18081
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres-data:
