spring:
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: library
